plugins {
    id 'com.android.application'
}

android {
    namespace 'kr.opencourse.gorotation'
    compileSdk 33

    defaultConfig {
        applicationId "kr.opencourse.gorotation"
        minSdkVersion 26
        targetSdkVersion 33
        versionCode 4
        versionName "1.1"

        resValue "string", "xposed_description", "Go Daijishou - LG Second Launcher to Rotate Screen by Husband of Rebekah"
        //resValue "string-array", "xposed_scope", "com.lge.secondlauncher"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // 디버그 키로 서명 - 키스토어 관리 없이 설치 가능한 APK 생성
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly(libs.xposed.api)
    compileOnly(libs.xposed.api.sources)
}